Metrics/ModuleLength:
  Max: 115

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 17

Metrics/PerceivedComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 85

Style/IdenticalConditionalBranches:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/GuardClause:
  Enabled: false
